export interface BacklinkPlatform {
  name: string;
  url: string;
  entryUrl: string;
  category: string;
  steps: string;
}

export const backlinkPlatforms: BacklinkPlatform[] = [
  { name: "LinkedIn", url: "https://www.linkedin.com", entryUrl: "https://www.linkedin.com/in/me/edit", category: "社交资料", steps: "登录 → 个人资料 → 编辑公开资料 → 联系信息/简介 → 添加网站URL" },
  { name: "Facebook", url: "https://www.facebook.com", entryUrl: "https://www.facebook.com/profile.php?sk=about_contact_and_basic_info", category: "社交资料", steps: "登录 → 个人资料 → 关于 → 联系信息和基本信息 → 添加网站/社交链接" },
  { name: "Twitter/X", url: "https://twitter.com", entryUrl: "https://twitter.com/settings/profile", category: "社交资料", steps: "登录 → 设置 → 个人资料 → 网站栏 → 输入URL → 保存" },
  { name: "Instagram", url: "https://www.instagram.com", entryUrl: "https://www.instagram.com/accounts/edit/", category: "社交资料", steps: "登录 → 编辑个人资料 → 网站栏 → 输入URL → 提交" },
  { name: "Pinterest", url: "https://www.pinterest.com", entryUrl: "https://www.pinterest.com/settings", category: "社交资料", steps: "登录 → 设置 → 个人资料 → 网站URL → 输入 → 保存" },
  { name: "Reddit", url: "https://www.reddit.com", entryUrl: "https://www.reddit.com/settings/profile", category: "社交资料", steps: "登录 → 用户设置 → 个人资料 → 社交链接 → 添加网站URL" },
  { name: "GitHub", url: "https://github.com", entryUrl: "https://github.com/settings/profile", category: "社交资料", steps: "登录 → Settings → Profile → URL栏 → 输入网站 → Update profile" },
  { name: "About.me", url: "https://about.me", entryUrl: "https://about.me/edit", category: "社交资料", steps: "登录 → Edit Profile → Links → 添加网站URL → Publish" },
  { name: "Linktree", url: "https://linktr.ee", entryUrl: "https://app.linktr.ee/dashboard", category: "社交资料", steps: "登录 → Dashboard → Links → 添加链接 → URL输入 → 保存" },
  { name: "Behance", url: "https://www.behance.net", entryUrl: "https://www.behance.net/settings", category: "社交资料", steps: "登录 → Settings → Profile → Websites → 添加URL → 保存" },
  { name: "Dribbble", url: "https://dribbble.com", entryUrl: "https://dribbble.com/account/edit", category: "社交资料", steps: "登录 → Edit Profile → Links → 添加网站 → Save" },
  { name: "Medium", url: "https://medium.com", entryUrl: "https://medium.com/me/settings", category: "Web 2.0", steps: "登录 → Settings → Profile → Links → 添加网站URL → Save" },
  { name: "Tumblr", url: "https://www.tumblr.com", entryUrl: "https://www.tumblr.com/settings", category: "Web 2.0", steps: "登录 → Settings → 选择博客 → Blog Settings → 输入网站URL → 保存" },
  { name: "WordPress.com", url: "https://wordpress.com", entryUrl: "https://wordpress.com/me/profile", category: "Web 2.0", steps: "登录 → Me → Profile → Website栏 → 输入URL → Save" },
  { name: "Blogger", url: "https://www.blogger.com", entryUrl: "https://www.blogger.com/profile/edit", category: "Web 2.0", steps: "登录 → Settings → User Profile → Website → 输入 → Save Profile" },
  { name: "Wix", url: "https://www.wix.com", entryUrl: "https://www.wix.com/dashboard", category: "Web 2.0", steps: "登录 → Dashboard → Settings → Contact Info → 添加网站 → 保存" },
  { name: "Weebly", url: "https://www.weebly.com", entryUrl: "https://www.weebly.com/dashboard", category: "Web 2.0", steps: "登录 → Dashboard → Editor → Settings → SEO → Website URL → 保存" },
  { name: "Jimdo", url: "https://www.jimdo.com", entryUrl: "https://www.jimdo.com/dashboard", category: "Web 2.0", steps: "登录 → Dashboard → Settings → SEO/Marketing → 添加网站URL → 保存" },
  { name: "Strikingly", url: "https://www.strikingly.com", entryUrl: "https://www.strikingly.com/dashboard", category: "Web 2.0", steps: "登录 → Dashboard → Settings → SEO → Website URL → 保存" },
  { name: "Hatena Blog", url: "https://hatenablog.com", entryUrl: "https://blog.hatena.ne.jp/-/config/profile", category: "Web 2.0", steps: "登录 → 設定 → プロフィール → URL欄 → 入力 → 保存" },
  { name: "DMOZ (AOL)", url: "https://dmoz-odp.org", entryUrl: "https://dmoz-odp.org/submit.html", category: "目录提交", steps: "访问提交页面 → 选择分类 → 输入网站信息 → 提交审核" },
  { name: "Hotfrog", url: "https://www.hotfrog.com", entryUrl: "https://www.hotfrog.com/add-business", category: "目录提交", steps: "点击Add Your Business → 填写公司名称/网站/描述 → Submit" },
  { name: "Kompass", url: "https://www.kompass.com", entryUrl: "https://www.kompass.com/addcompany", category: "目录提交", steps: "登录 → Add Company → 输入公司网站 → 提交审核" },
  { name: "Yelp", url: "https://www.yelp.com", entryUrl: "https://www.yelp.com/claim", category: "目录提交", steps: "搜索你的商家 → Claim this business → 验证后编辑网站URL → Save" },
  { name: "BBB", url: "https://www.bbb.org", entryUrl: "https://www.bbb.org/claim-your-business", category: "目录提交", steps: "搜索商家 → Claim → 验证 → 编辑Business Profile → 添加网站URL" },
  { name: "Manta", url: "https://www.manta.com", entryUrl: "https://www.manta.com/add-a-business", category: "目录提交", steps: "Add your business → 填写网站 → 提交 → 验证" },
  { name: "Cylex US", url: "https://www.cylex.us.com", entryUrl: "https://www.cylex.us.com/add.aspx", category: "目录提交", steps: "Add your business → 填写公司信息 → 输入网站URL → Submit" },
  { name: "EzineArticles", url: "https://ezinearticles.com", entryUrl: "https://ezinearticles.com/members/memberarea.php", category: "文章提交", steps: "注册 → Member Area → Submit Article → Author Resource Box → 添加网站链接" },
  { name: "Articles Factory", url: "https://articlesfactory.com", entryUrl: "https://articlesfactory.com/login/submit-articles", category: "文章提交", steps: "注册登录 → Submit Article → 输入文章 → Author Bio → 添加URL → Submit" },
  { name: "Sooper Articles", url: "https://www.sooperarticles.com", entryUrl: "https://www.sooperarticles.com/submit-articles.php", category: "文章提交", steps: "注册 → Submit Article → About Author栏 → 添加网站链接 → Submit" },
  { name: "Article City", url: "https://articlecity.com", entryUrl: "https://articlecity.com/submit-article", category: "文章提交", steps: "注册 → Submit Article → Author Bio → 填网站URL → Submit" },
  { name: "Articlesnatch", url: "https://www.articlesnatch.com", entryUrl: "https://www.articlesnatch.com/submit-article", category: "文章提交", steps: "注册 → Submit Article → Resource Box → 添加网站链接 → Submit" },
  { name: "Diigo", url: "https://www.diigo.com", entryUrl: "https://www.diigo.com/bookmark", category: "书签", steps: "登录 → My Bookmarks → Add Bookmarks → 输入URL/Title/Description → Save" },
  { name: "Scoop.it", url: "https://www.scoop.it", entryUrl: "https://www.scoop.it/settings/curation", category: "书签", steps: "登录 → Settings → Curation → Your Website → 输入URL → Save" },
  { name: "Mix", url: "https://mix.com", entryUrl: "https://mix.com/add", category: "书签", steps: "登录 → Add → 输入网站URL → 添加描述 → Submit" },
  { name: "BibSonomy", url: "https://www.bibsonomy.org", entryUrl: "https://www.bibsonomy.org/addBookmark", category: "书签", steps: "登录 → Add Bookmark → 输入URL/Title/Description → Save" },
  { name: "Pearltrees", url: "https://www.pearltrees.com", entryUrl: "https://www.pearltrees.com/addurl", category: "书签", steps: "登录 → Add Page → 输入URL → Add to Pearltree → 组织收藏" },
  { name: "Quora", url: "https://www.quora.com", entryUrl: "https://www.quora.com/settings/profile", category: "问答", steps: "登录 → 设置 → Profile → 添加网站URL → Save Changes" },
  { name: "Stack Overflow", url: "https://stackoverflow.com", entryUrl: "https://stackoverflow.com/users/edit/current", category: "问答", steps: "登录 → Edit Profile → Links → 输入网站URL → Save" },
  { name: "Yahoo Answers", url: "https://answers.yahoo.com", entryUrl: "https://answers.yahoo.com/profile/edit", category: "问答", steps: "登录 → Profile → Edit → 添加Website → Save" },
  { name: "Answerbag", url: "https://www.answerbag.com", entryUrl: "https://www.answerbag.com/profile/edit_profile", category: "问答", steps: "登录 → My Profile → Edit → Website栏 → 输入URL → Update" },
  { name: "Ask.fm", url: "https://ask.fm", entryUrl: "https://ask.fm/settings/profile", category: "问答", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "YouTube", url: "https://www.youtube.com", entryUrl: "https://studio.youtube.com", category: "媒体分享", steps: "登录 → YouTube Studio → Customization → Basic Info → Links → 添加URL → Publish" },
  { name: "SlideShare", url: "https://www.slideshare.net", entryUrl: "https://www.slideshare.net/settings", category: "媒体分享", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "Issuu", url: "https://issuu.com", entryUrl: "https://issuu.com/settings/profile", category: "媒体分享", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "Scribd", url: "https://www.scribd.com", entryUrl: "https://www.scribd.com/account-settings", category: "媒体分享", steps: "登录 → Account Settings → Profile → Website → 输入URL → Save" },
  { name: "Flickr", url: "https://www.flickr.com", entryUrl: "https://www.flickr.com/profile/edit", category: "媒体分享", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "500px", url: "https://500px.com", entryUrl: "https://500px.com/settings", category: "媒体分享", steps: "登录 → Settings → Profile → Web → 输入URL → Save" },
  { name: "Vimeo", url: "https://vimeo.com", entryUrl: "https://vimeo.com/settings", category: "媒体分享", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "Dailymotion", url: "https://www.dailymotion.com", entryUrl: "https://www.dailymotion.com/settings/channel", category: "媒体分享", steps: "登录 → Settings → Channel → Website → 输入URL → Save" },
  { name: "Imgur", url: "https://imgur.com", entryUrl: "https://imgur.com/account/settings", category: "媒体分享", steps: "登录 → Account Settings → Profile → Website → 输入URL → Update" },
  { name: "DeviantArt", url: "https://www.deviantart.com", entryUrl: "https://www.deviantart.com/settings/profile", category: "媒体分享", steps: "登录 → Settings → Profile → Website → 输入URL → Apply" },
  { name: "Moz Blog", url: "https://moz.com/blog", entryUrl: "https://moz.com/community/write-for-us", category: "客座博客", steps: "访问贡献页面 → 阅读指南 → 提交文章提案 → 审核通过后发表(包含作者bio链接)" },
  { name: "Search Engine Land", url: "https://searchengineland.com", entryUrl: "https://searchengineland.com/contribute", category: "客座博客", steps: "访问Contribute页面 → 阅读指南 → 提交文章 → 通过后获得作者简介+链接" },
  { name: "Neil Patel", url: "https://neilpatel.com", entryUrl: "https://neilpatel.com/guest-post/", category: "客座博客", steps: "访问Guest Post页 → 填写提案表单 → 审核通过 → 文章含作者bio链接" },
  { name: "Search Engine Journal", url: "https://www.searchenginejournal.com", entryUrl: "https://www.searchenginejournal.com/write-for-us/", category: "客座博客", steps: "访问Write for Us → 提交文章提案 → 审核 → 发表含作者简介+链接" },
  { name: "HubSpot Blog", url: "https://blog.hubspot.com", entryUrl: "https://www.hubspot.com/guest-post-submission", category: "客座博客", steps: "访问Guest Post Submission → 提交提案 → 审核通过 → 文章含网站链接" },
  { name: "Smashing Magazine", url: "https://www.smashingmagazine.com", entryUrl: "https://www.smashingmagazine.com/write-for-us/", category: "客座博客", steps: "访问Write for Us → 提交文章大纲 → 审核 → 发表含作者bio+链接" },
  { name: "CSS-Tricks", url: "https://css-tricks.com", entryUrl: "https://css-tricks.com/contact/", category: "客座博客", steps: "访问Contact → 通过邮件/表单提交投稿 → 审核通过后含作者链接" },
  { name: "Entrepreneur", url: "https://www.entrepreneur.com", entryUrl: "https://www.entrepreneur.com/contributor", category: "客座博客", steps: "访问Contributor页 → 申请成为贡献者 → 审核通过后发表含bio链接" },
  { name: "Business 2 Community", url: "https://www.business2community.com", entryUrl: "https://www.business2community.com/write-for-us", category: "客座博客", steps: "访问Write for Us → 提交提案 → 审核通过 → 作者简介含网站URL" },
  { name: "HuffPost", url: "https://www.huffpost.com", entryUrl: "https://contribute.huffpost.com", category: "客座博客", steps: "访问Contributor Platform → 注册 → 提交文章 → 审核通过后含作者简介链接" },
  { name: "Digital Point", url: "https://forums.digitalpoint.com", entryUrl: "https://forums.digitalpoint.com/account/profile", category: "论坛", steps: "注册/登录 → Profile → Signature → 输入网站链接 → Save" },
  { name: "WebmasterWorld", url: "https://www.webmasterworld.com", entryUrl: "https://www.webmasterworld.com/profile/edit", category: "论坛", steps: "登录 → Profile → Edit Signature → 添加网站URL → Save" },
  { name: "Warrior Forum", url: "https://www.warriorforum.com", entryUrl: "https://www.warriorforum.com/profile.php?do=editprofile", category: "论坛", steps: "登录 → Settings → Edit Profile → Signature → 添加网站URL → Save" },
  { name: "PRLog", url: "https://www.prlog.org", entryUrl: "https://www.prlog.org/login.html", category: "新闻稿", steps: "注册/登录 → Submit Press Release → 输入新闻稿 → 添加网站/Links → Submit" },
  { name: "PRFree", url: "https://prfree.org", entryUrl: "https://prfree.org/submit", category: "新闻稿", steps: "注册 → Submit → News → Include URLs in article body → Submit for review" },
  { name: "1888 PressRelease", url: "https://www.1888pressrelease.com", entryUrl: "https://www.1888pressrelease.com/submit-pr.html", category: "新闻稿", steps: "注册 → Submit Press Release → 编辑发布内容 → 含网站链接 → Submit" },
  { name: "Newswire", url: "https://www.newswire.com", entryUrl: "https://www.newswire.com/account", category: "新闻稿", steps: "注册/登录 → Create Release → 撰写 → 含Company Website → Distribute" },
  { name: "Academia.edu", url: "https://www.academia.edu", entryUrl: "https://www.academia.edu/settings", category: "高校", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
  { name: "ResearchGate", url: "https://www.researchgate.net", entryUrl: "https://www.researchgate.net/profile/me/settings", category: "高校", steps: "登录 → Settings → Profile → Website → 输入URL → Save" },
];

export const categories = [...new Set(backlinkPlatforms.map(p => p.category))];
