import './navigation.js';
import './interaction.js';
import './query.js';
import './wait.js';
import './scroll.js';
import './mouse.js';
import './find-visual.js';
import './vision-task.js';
import './evaluate.js';
import './ua.js';
import './storage.js';
import './screenshot.js';
import './structure.js';
import './viewport.js';
import './frame.js';
import './ui-debug.js';
import './actions.js';
import './scrape.js';
import './map.js';
import './crawl.js';
import './search.js';
import './network.js';
import './ai-search-engines.js';
import './snapshot.js';
import './agent.js';
import './tab.js';
import './addinitscript.js';
import './find.js';
import './detect.js';
import './visual-tag.js';
import './visual-tag-v2.js';

export { getCommand, getAllCommands, getCommandNames, clearRegistry, registerCommand } from './command-registry.js';
export type { RegisteredCommand, BrowserCommandDefinition } from './command-registry.js';
