import './navigation.js';
import './interaction.js';
import './query.js';
import './wait.js';
import './scroll.js';
import './mouse.js';
import './evaluate.js';
import './storage.js';
import './snapshot.js';
import './structure.js';
import './viewport.js';
import './frame.js';
import './ui-test.js';
import './ui-debug.js';
import './actions.js';
import './scrape.js';
import './map.js';
import './crawl.js';
import './search.js';

export { getCommand, getAllCommands, getCommandNames, clearRegistry, registerCommand } from './command-registry.js';
export type { RegisteredCommand, BrowserCommandDefinition } from './command-registry.js';
